# LoadBalancer Service. Will only work on supported cloud platforms (AKS, EKS, GKE, DOK, IBM etc...)
# Listens on 80 and forwards to Pod/container on 8080
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
