# Simple Kubernetes Pod to deploy the app contained in nigelpoulton/ps-web:1.0
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: web-ctr
      image: nigelpoulton/ps-web:1.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8080